import type { APIRoute } from "astro";
import { getArticulos } from "../../lib/googleSheets.ts";
import { MODE } from "astro:env/server";

const mockarticulos = [
  {
    codigo: "1006",
    categoria: "Helado",
    descripcion: "1/4 kg helado",
    precio: "1",
  },
  {
    codigo: "1007",
    categoria: "Helado",
    descripcion: "1/2 kg helado",
    precio: "1",
  },
  {
    codigo: "1009",
    categoria: "Helado",
    descripcion: "1kg helado",
    precio: "1",
  },
  {
    codigo: "6002",
    categoria: "Helado",
    descripcion: "Promo kilo y medio",
    precio: "1",
  },
  {
    codigo: "1004",
    categoria: "Cucurucho",
    descripcion: "Cucurucho chico 2 bochas",
    precio: "1",
  },
  {
    codigo: "1005",
    categoria: "Cucurucho",
    descripcion: "Cucurucho grande 2 bochas",
    precio: "1",
  },
  {
    codigo: "1002",
    categoria: "Vasos",
    descripcion: "Vaso chico 2 bochas",
    precio: "1",
  },
  {
    codigo: "1003",
    categoria: "Vasos",
    descripcion: "Vaso grande 2 bochas ",
    precio: "1",
  },
  {
    codigo: "1001",
    categoria: "Vasos",
    descripcion: "Vaso 1 bocha",
    precio: "1",
  },
  {
    codigo: "1029",
    categoria: "Alfajor",
    descripcion: "Alfajor helado",
    precio: "1",
  },
  {
    codigo: "1028",
    categoria: "Palitos helados",
    descripcion: "Palito bombón",
    precio: "1",
  },
  {
    codigo: "1030",
    categoria: "Palitos helados",
    descripcion: "Palito de frutilla/limón",
    precio: "1",
  },
  {
    codigo: "1031",
    categoria: "Palitos helados",
    descripcion: "Palitos x10",
    precio: "1",
  },
  {
    codigo: "1039",
    categoria: "Milkshake ",
    descripcion: "Milkshake",
    precio: "1",
  },
  {
    codigo: "1042",
    categoria: "Postres y tortas",
    descripcion: "Bombón escoces x6 Pistaccio",
    precio: "1",
  },
  {
    codigo: "1025",
    categoria: "Postres y tortas",
    descripcion: "Postres 1/2 barra Baileys/Frutal/Tentación",
    precio: "1",
  },
  {
    codigo: "1020",
    categoria: "Postres y tortas",
    descripcion: "Torta frutilla/ merengada",
    precio: "1",
  },
  {
    codigo: "1021",
    categoria: "Postres y tortas",
    descripcion: "Torta nuez / almendra",
    precio: "1",
  },
  {
    codigo: "1032",
    categoria: "Postres y tortas",
    descripcion: "Bombón suizo x8",
    precio: "1",
  },
  {
    codigo: "1043",
    categoria: "Postres y tortas",
    descripcion: "BOMBON ESCOCES DE PISTACHO",
    precio: "1",
  },
  {
    codigo: "1044",
    categoria: "Postres y tortas",
    descripcion: "ALFAJOR FRUTOS ROJOS",
    precio: "1",
  },
  {
    codigo: "1033",
    categoria: "Postres y tortas",
    descripcion: "Bombón escoces x6",
    precio: "1",
  },
  {
    codigo: "1034",
    categoria: "Postres y tortas",
    descripcion: "Alfajor helado x6",
    precio: "1",
  },
  {
    codigo: "1044",
    categoria: "Postres y tortas",
    descripcion: "Alfajor helado Frutos del Bosque x6",
    precio: "1",
  },
  {
    codigo: "1037",
    categoria: "Helado sin TACC",
    descripcion: "Pote sin TACC 200cc",
    precio: "1",
  },
  {
    codigo: "1038",
    categoria: "Helado sin TACC",
    descripcion: "Pote sin TACC 500cc",
    precio: "1",
  },
  {
    codigo: "1016",
    categoria: "Copas y bandejas",
    descripcion: "Copa chica",
    precio: "1",
  },
  {
    codigo: "1017",
    categoria: "Copas y bandejas",
    descripcion: "Copa grande",
    precio: "1",
  },
  {
    codigo: "5002",
    categoria: "Copas y bandejas",
    descripcion: "Toppings y salsas",
    precio: "1",
  },
  {
    codigo: "1018",
    categoria: "Copas y bandejas",
    descripcion: "Bandeja grande",
    precio: "1",
  },
  {
    codigo: "5004",
    categoria: "Blister",
    descripcion: "Blister de cucuruchos x4",
    precio: "1",
  },
  {
    codigo: "5001",
    categoria: "Cobertura de chocolate",
    descripcion: "Cobertura de chocolate",
    precio: "1",
  },
  {
    codigo: "6666",
    categoria: "Cumpleaños",
    descripcion: "1/4 gratis",
    precio: "1",
  },
  {
    codigo: "6667",
    categoria: "Cumpleaños",
    descripcion: "Pote 200cc SIN TACC",
    precio: "1",
  },
  {
    codigo: "6015",
    categoria: "Helado",
    descripcion: '"Pedí temprano" 1k - 30%off',
    precio: "1",
  },
  {
    codigo: "6031",
    categoria: "Helado",
    descripcion: '"Promo reyes" 1/4 - 50%off',
    precio: "1",
  },
  {
    codigo: "6070",
    categoria: "HANKS",
    descripcion: "1/4 hANKS",
    precio: "1",
  },
  {
    codigo: "6069",
    categoria: "HANKS",
    descripcion: "1/2 HANKS",
    precio: "1",
  },
  {
    codigo: "6024",
    categoria: "Helado",
    descripcion: "1/4 khg 50 % OFF",
    precio: "1",
  },
  {
    codigo: "6666",
    categoria: "Helado",
    descripcion: "cumpleaños 1/4 sin cargo",
    precio: "1",
  },
  {
    codigo: "10",
    categoria: "Helado a granel ",
    descripcion: "1/4kg - 15% off",
    precio: "1",
  },
  {
    codigo: "11",
    categoria: "Helado a granel ",
    descripcion: "1/2kg - 10% off",
    precio: "1",
  },
  {
    codigo: "12",
    categoria: "Helado a granel ",
    descripcion: "kilo y medio - 10% off",
    precio: "1",
  },
  {
    codigo: "13",
    categoria: "Helado a granel ",
    descripcion: "1kilo - 15% off",
    precio: "1",
  },
  {
    codigo: "16",
    categoria: "Sin TACC",
    descripcion: "Pote 200cc - 10% off",
    precio: "1",
  },
  {
    codigo: "17",
    categoria: "Sin TACC",
    descripcion: "Pote 500cc - 10% off",
    precio: "1",
  },
  {
    codigo: "18",
    categoria: "Postres y tortas",
    descripcion: "Torta frut/meren/selva - 10% off",
    precio: "1",
  },
  {
    codigo: "19",
    categoria: "Postres y tortas",
    descripcion: "Torta almendras/nuez - 10% off",
    precio: "1",
  },
  {
    codigo: "20",
    categoria: "Postres y tortas",
    descripcion: "Bombón escoces - 10% off",
    precio: "1",
  },
  {
    codigo: "21",
    categoria: "Postres y tortas",
    descripcion: "Bombón suizo - 10% off",
    precio: "1",
  },
  {
    codigo: "22",
    categoria: "Postres y tortas",
    descripcion: "Alfajor x6 - 10% off",
    precio: "1",
  },
  {
    codigo: "23",
    categoria: "Postres y tortas",
    descripcion: "Postre tentación - 10% off",
    precio: "1",
  },
  {
    codigo: "24",
    categoria: "Postres y tortas",
    descripcion: "Postre frutal - 10% off",
    precio: "1",
  },
  {
    codigo: "25",
    categoria: "Postres y tortas",
    descripcion: "Postre Baileys - 10% off",
    precio: "1",
  },
  {
    codigo: "26",
    categoria: "Palitos de agua",
    descripcion: "Palitos de agua x10 - 10% off",
    precio: "1",
  },
  {
    codigo: "4015",
    categoria: "Brocatta",
    descripcion: "Limonada 1L + 2 brocattas",
    precio: "1",
  },
  {
    codigo: "4016",
    categoria: "Waffle relleno",
    descripcion: "Waffle relleno + Gaseosa o saborizada",
    precio: "1",
  },
  {
    codigo: "4017",
    categoria: "Tostado",
    descripcion: "Tostado + Gaseosa o saborizada",
    precio: "1",
  },
  {
    codigo: "4018",
    categoria: "Brocatta",
    descripcion: "Brocatta + Gaseosa o saborizada",
    precio: "1",
  },
  {
    codigo: "4019",
    categoria: "Yogurt",
    descripcion: "Yogurt + Jugo de naranja",
    precio: "1",
  },
  {
    codigo: "2001",
    categoria: "Café CHICO",
    descripcion: "Grano extra",
    precio: "1",
  },
  {
    codigo: "2048",
    categoria: "Café CHICO",
    descripcion: "Ristretto Italiano",
    precio: "1",
  },
  {
    codigo: "2049",
    categoria: "Café CHICO",
    descripcion: "Colombiano",
    precio: "1",
  },
  {
    codigo: "2056",
    categoria: "Café CHICO",
    descripcion: "Ethiope",
    precio: "1",
  },
  {
    codigo: "2002",
    categoria: "Café MEDIANO",
    descripcion: "Grano extra",
    precio: "1",
  },
  {
    codigo: "2044",
    categoria: "Café MEDIANO",
    descripcion: "Ristretto Italiano",
    precio: "1",
  },
  {
    codigo: "2003",
    categoria: "Café MEDIANO",
    descripcion: "Colombiano",
    precio: "1",
  },
  {
    codigo: "2061",
    categoria: "Café MEDIANO",
    descripcion: "Ethiope",
    precio: "1",
  },
  {
    codigo: "2058",
    categoria: "CAFÉ CON LECHE-lágrima GRANDE",
    descripcion: "Grano extra",
    precio: "1",
  },
  {
    codigo: "2063",
    categoria: "CAFÉ CON LECHE-lágrima GRANDE",
    descripcion: "Ristretto Italiano",
    precio: "1",
  },
  {
    codigo: "2063",
    categoria: "CAFÉ CON LECHE-lágrima GRANDE",
    descripcion: "Colombiano",
    precio: "1",
  },
  {
    codigo: "2065",
    categoria: "CAFÉ CON LECHE-lágrima GRANDE",
    descripcion: "Ethiope",
    precio: "1",
  },
  {
    codigo: "2042",
    categoria: "CAFÉ SOLO- cortado GRANDE",
    descripcion: "Grano extra",
    precio: "1",
  },
  {
    codigo: "2051",
    categoria: "CAFÉ SOLO- cortado GRANDE",
    descripcion: "Ristretto Italiano",
    precio: "1",
  },
  {
    codigo: "2052",
    categoria: "CAFÉ SOLO- cortado GRANDE",
    descripcion: "Colombiano",
    precio: "1",
  },
  {
    codigo: "2062",
    categoria: "CAFÉ SOLO- cortado GRANDE",
    descripcion: "Ethiope",
    precio: "1",
  },
  {
    codigo: "2066",
    categoria: "CAFÉ CON LECHE-lágrima EXTRA LARGE",
    descripcion: "Grano extra",
    precio: "1",
  },
  {
    codigo: "2067",
    categoria: "CAFÉ CON LECHE-lágrima EXTRA LARGE",
    descripcion: "Ristretto Italiano",
    precio: "1",
  },
  {
    codigo: "2068",
    categoria: "CAFÉ CON LECHE-lágrima EXTRA LARGE",
    descripcion: "Colombiano",
    precio: "1",
  },
  {
    codigo: "2069",
    categoria: "CAFÉ CON LECHE-lágrima EXTRA LARGE",
    descripcion: "Ethiope",
    precio: "1",
  },
  {
    codigo: "2053",
    categoria: "CAFÉ SOLO-cortado EXTRA LARGE",
    descripcion: "Grano extra",
    precio: "1",
  },
  {
    codigo: "2054",
    categoria: "CAFÉ SOLO-cortado EXTRA LARGE",
    descripcion: "Ristretto Italiano",
    precio: "1",
  },
  {
    codigo: "2055",
    categoria: "CAFÉ SOLO-cortado EXTRA LARGE",
    descripcion: "Colombiano",
    precio: "1",
  },
  {
    codigo: "2045",
    categoria: "CAFÉ SOLO-cortado EXTRA LARGE",
    descripcion: "Ethiope",
    precio: "1",
  },
  {
    codigo: "2011",
    categoria: "Cafés y otros con nombre y apellido",
    descripcion: "American coffee",
    precio: "1",
  },
  {
    codigo: "2012",
    categoria: "Cafés y otros con nombre y apellido",
    descripcion: "American cream coffe",
    precio: "1",
  },
  {
    codigo: "2013",
    categoria: "Cafés y otros con nombre y apellido",
    descripcion: "Café Irlandés",
    precio: "1",
  },
  {
    codigo: "2014",
    categoria: "Cafés y otros con nombre y apellido",
    descripcion: "Astor",
    precio: "1",
  },
  {
    codigo: "2005",
    categoria: "Cafés y otros con nombre y apellido",
    descripcion: "Remo (Submarino)",
    precio: "1",
  },
  {
    codigo: "2007",
    categoria: "Cafés y otros con nombre y apellido",
    descripcion: "Capuchino",
    precio: "1",
  },
  {
    codigo: "2015",
    categoria: "Cafés y otros con nombre y apellido",
    descripcion: "Latte Moka",
    precio: "1",
  },
  {
    codigo: "2016",
    categoria: "Cafés y otros con nombre y apellido",
    descripcion: "Leche chocolatada",
    precio: "1",
  },
  {
    codigo: "2017",
    categoria: "Cafés y otros con nombre y apellido",
    descripcion: "Café Bombón",
    precio: "1",
  },
  {
    codigo: "2018",
    categoria: "Cafés y otros con nombre y apellido",
    descripcion: "Orange black",
    precio: "1",
  },
  {
    codigo: "2004",
    categoria: "Infusiones",
    descripcion: "Té - mate cocido solo o con leche",
    precio: "1",
  },
  {
    codigo: "2019",
    categoria: "Infusiones",
    descripcion: "Té especiales / Té en hebras blend",
    precio: "1",
  },
  {
    codigo: "3038",
    categoria: "MUFFIN",
    descripcion: "MUFFIN MANZANA",
    precio: "1",
  },
  {
    codigo: "3006",
    categoria: "Cookies sin tacc",
    descripcion: "cooki sin tacc x 1",
    precio: "1",
  },
  {
    codigo: "3005",
    categoria: "Cookies sin tacc",
    descripcion: "cooki sin tacc x 2",
    precio: "1",
  },
  {
    codigo: "2024",
    categoria: "Tostadas",
    descripcion: "3 tostadas sin TACC",
    precio: "1",
  },
  {
    codigo: "3025",
    categoria: "CAMPESTRE",
    descripcion: "Tostadas + porción de queso y mermelada",
    precio: "1",
  },
  {
    codigo: "2026",
    categoria: "Chipá",
    descripcion: "Chipá x4",
    precio: "1",
  },
  {
    codigo: "3050",
    categoria: "Chipá",
    descripcion: "CHIPA GRANDE UNIDAD",
    precio: "1",
  },
  {
    codigo: "2021",
    categoria: "Tartas",
    descripcion: "TARTA INDIV DE ESPINACAS",
    precio: "1",
  },
  {
    codigo: "3049",
    categoria: "Alfajores",
    descripcion: "ALFAJOR DE PISTACHO",
    precio: "1",
  },
  {
    codigo: "3048",
    categoria: "Alfajores",
    descripcion: "ALFAJOR DE CHOCOLATE",
    precio: "1",
  },
  {
    codigo: "3042",
    categoria: "MINI CAKES",
    descripcion: " MARQUISE",
    precio: "1",
  },
  {
    codigo: "3043",
    categoria: "MINI CAKES",
    descripcion: "LEMON PIE",
    precio: "1",
  },
  {
    codigo: "3044",
    categoria: "MINI CAKES",
    descripcion: "CHOCOTORTA",
    precio: "1",
  },
  {
    codigo: "3045",
    categoria: "MINI CAKES",
    descripcion: "MOUSSE DE CHOCOLATE",
    precio: "1",
  },
  {
    codigo: "3046",
    categoria: "MINI CAKES",
    descripcion: "CHEESCAKE MARACUYA",
    precio: "1",
  },
  {
    codigo: "3046",
    categoria: "MINI CAKES",
    descripcion: "CHEESCAKE DULCE DE LECHE",
    precio: "1",
  },
  {
    codigo: "3046",
    categoria: "MINI CAKES",
    descripcion: "CHEESCAKE FRUTOS ROJOS",
    precio: "1",
  },
  {
    codigo: "3042",
    categoria: "MINI CAKES",
    descripcion: "SUPREME",
    precio: "1",
  },
  {
    codigo: "3042",
    categoria: "MINI CAKES",
    descripcion: "ROGEL",
    precio: "1",
  },
  {
    codigo: "3042",
    categoria: "MINI CAKES",
    descripcion: "SACHER",
    precio: "1",
  },
  {
    codigo: "9001",
    categoria: "Salados",
    descripcion: "Tostado de jamón y queso",
    precio: "1",
  },
  {
    codigo: "3001",
    categoria: "Salados",
    descripcion: "Medialunas",
    precio: "1",
  },
  {
    codigo: "2060",
    categoria: "Salados",
    descripcion: "Medialunas con jamón y queso",
    precio: "1",
  },
  {
    codigo: "3026",
    categoria: "Salados",
    descripcion: "Chipá x4",
    precio: "1",
  },
  {
    codigo: "2030",
    categoria: "Salados",
    descripcion: "Brocatta x1",
    precio: "1",
  },
  {
    codigo: "2029",
    categoria: "Salados",
    descripcion: "Brocatta x2",
    precio: "1",
  },
  {
    codigo: "2033",
    categoria: "Waffles ",
    descripcion: "Waffle salado relleno",
    precio: "1",
  },
  {
    codigo: "2075",
    categoria: "Waffles ",
    descripcion: "WAFFLE SALADO RELLENO COMPLETO",
    precio: "1",
  },
  {
    codigo: "2032",
    categoria: "Waffles ",
    descripcion: "Waffle con salsa",
    precio: "1",
  },
  {
    codigo: "2031",
    categoria: "Waffles ",
    descripcion: "Waffle con dulce de leche",
    precio: "1",
  },
  {
    codigo: "3023",
    categoria: "Waffles ",
    descripcion: "Waffle con helado",
    precio: "1",
  },
  {
    codigo: "2035",
    categoria: "Waffles ",
    descripcion: "Mini waffle con helado",
    precio: "1",
  },
  {
    codigo: "2034",
    categoria: "Waffles ",
    descripcion: "Waffle con frutas",
    precio: "1",
  },
  {
    codigo: "3002",
    categoria: "Dulces",
    descripcion: "Brownie",
    precio: "1",
  },
  {
    codigo: "3003",
    categoria: "Dulces",
    descripcion: "Churros rellenos",
    precio: "1",
  },
  {
    codigo: "3034",
    categoria: "Dulces",
    descripcion: "Alfajor chocolate-maicena",
    precio: "1",
  },
  {
    codigo: "2028",
    categoria: "Dulces",
    descripcion: "Alfajor frutilla-manzana",
    precio: "1",
  },
  {
    codigo: "3008",
    categoria: "Dulces",
    descripcion: "Lingotes (todos",
    precio: "1",
  },
  {
    codigo: "3022",
    categoria: "Dulces",
    descripcion: "Brownie con helado",
    precio: "1",
  },
  {
    codigo: "2036",
    categoria: "Dulces",
    descripcion: "Yogurt griego con granola y frutos secos",
    precio: "1",
  },
  {
    codigo: "2041",
    categoria: "Medialunas LSM",
    descripcion: "Medialunas dulces y saladas unidad",
    precio: "1",
  },
  {
    codigo: "2071",
    categoria: "Medialunas LSM",
    descripcion: "Medialunas 1/2docena",
    precio: "1",
  },
  {
    codigo: "2072",
    categoria: "Medialunas LSM",
    descripcion: "Medialunas docena",
    precio: "1",
  },
  {
    codigo: "6081",
    categoria: "POP CORN",
    descripcion: "POP CORN",
    precio: "1",
  },
  {
    codigo: "2026",
    categoria: "Cookies",
    descripcion: "cookie con chips x1",
    precio: "1",
  },
  {
    codigo: "2027",
    categoria: "Cookies",
    descripcion: "cookie con chips x2",
    precio: "1",
  },
  {
    codigo: "4004",
    categoria: "Medialunas",
    descripcion: "Café/Té/Mate c. con leche + 2 medialunas ",
    precio: "1",
  },
  {
    codigo: "2059",
    categoria: "Tostado",
    descripcion: "Café/Té/Mate c. con leche con tostado",
    precio: "1",
  },
  {
    codigo: "4020",
    categoria: "Alfajor",
    descripcion: "Café/Té/Mate c. con leche con alfajor",
    precio: "1",
  },
  {
    codigo: "4013",
    categoria: "Medialunas rellenas",
    descripcion: "Café/Té/Mate c. con leche + 2 medialunas rellenas",
    precio: "1",
  },
  {
    codigo: "4021",
    categoria: "Waffle relleno",
    descripcion: "Café/Té/Mate  c. con leche + waffle relleno",
    precio: "1",
  },
  {
    codigo: "4022",
    categoria: "Lingote",
    descripcion: "Submarino + torta individual ",
    precio: "1",
  },
  {
    codigo: "4023",
    categoria: "Waffle relleno",
    descripcion: "Submarino + Waffle relleno",
    precio: "1",
  },
  {
    codigo: "4028",
    categoria: "Tostadas",
    descripcion: "Café/Té/Mate c. + tostadas ",
    precio: "1",
  },
  {
    codigo: "4006",
    categoria: "Merienda de campo",
    descripcion: "Café/Té/Mate c. + tostadas con mermelada y queso",
    precio: "1",
  },
  {
    codigo: "4029",
    categoria: "Medialunas",
    descripcion: "Jugo de naranja + 2medialunas",
    precio: "1",
  },
  {
    codigo: "4007",
    categoria: "Churros",
    descripcion: "Café + 2 churros",
    precio: "1",
  },
  {
    codigo: "4012",
    categoria: "Medialuna rellena",
    descripcion: "Café mediano + 1medialuna rellena",
    precio: "1",
  },
  {
    codigo: "2073",
    categoria: "Medialunas",
    descripcion: "2 medialunas LSM + café con leche",
    precio: "1",
  },
  {
    codigo: "4024",
    categoria: "Waffle relleno",
    descripcion: "Cerveza Sta Fé + waffle relleno",
    precio: "1",
  },
  {
    codigo: "4025",
    categoria: "Waffle relleno",
    descripcion: "Jugo de naranja + waffle relleno",
    precio: "1",
  },
  {
    codigo: "4026",
    categoria: "Tostado",
    descripcion: "Tostado + gaseosa o saborizada",
    precio: "1",
  },
  {
    codigo: "4027",
    categoria: "Tostado",
    descripcion: "Tostado + 2 cervezas Sta Fé",
    precio: "1",
  },
  {
    codigo: "4030",
    categoria: "Combo 1",
    descripcion: "2 café c leche + 2 jugos (chicos) + 1 tostado",
    precio: "1",
  },
  {
    codigo: "4031",
    categoria: "Combo 2",
    descripcion: "2 café c leche + tostadas c mermelada y queso + 4 churros",
    precio: "1",
  },
  {
    codigo: "4032",
    categoria: "Combo SORPRESA!!",
    descripcion: " 2 café con leche + 2 cookies con chips + 1 muffin",
    precio: "1",
  },
  {
    codigo: "8004",
    categoria: "Aguas",
    descripcion: "Agua mineral",
    precio: "1",
  },
  {
    codigo: "8007",
    categoria: "Aguas",
    descripcion: "Agua saborizada",
    precio: "1",
  },
  {
    codigo: "8001",
    categoria: "Gaseosas",
    descripcion: "Coca/Sprite/Fanta botella",
    precio: "1",
  },
  {
    codigo: "8025",
    categoria: "Gaseosas",
    descripcion: "Coca cola Zero",
    precio: "1",
  },
  {
    codigo: "8009",
    categoria: "Cervezas en lata",
    descripcion: "Budweiser ",
    precio: "1",
  },
  {
    codigo: "8010",
    categoria: "Cervezas en lata",
    descripcion: "Miller ",
    precio: "1",
  },
  {
    codigo: "8026",
    categoria: "Cervezas en lata",
    descripcion: "Santá Fé ",
    precio: "1",
  },
  {
    codigo: "8011",
    categoria: "Cervezas en lata",
    descripcion: "Quilmes negra",
    precio: "1",
  },
  {
    codigo: "8012",
    categoria: "Cervezas en lata",
    descripcion: "Schneider negra",
    precio: "1",
  },
  {
    codigo: "8013",
    categoria: "Whiskys",
    descripcion: "Whisky JEMERSON",
    precio: "1",
  },
  {
    codigo: "8014",
    categoria: "Whiskys",
    descripcion: "Whisky JACK DANIELS",
    precio: "1",
  },
  {
    codigo: "8015",
    categoria: "Whiskys",
    descripcion: "Whisky CHIVAS REGAL",
    precio: "1",
  },
  {
    codigo: "8016",
    categoria: "Whiskys",
    descripcion: "Whisky BLACK LABEL",
    precio: "1",
  },
  {
    codigo: "8017",
    categoria: "Whiskys",
    descripcion: "Whisky RED LABEL",
    precio: "1",
  },
  {
    codigo: "8018",
    categoria: "Licuados",
    descripcion: "Licuado de fruta con leche",
    precio: "1",
  },
  {
    codigo: "8019",
    categoria: "Licuados",
    descripcion: "Licuado de fruta con agua",
    precio: "1",
  },
  {
    codigo: "8020",
    categoria: "Licuados",
    descripcion: "Licuado mix frutos rojos - frutos tropicales",
    precio: "1",
  },
  {
    codigo: "1040",
    categoria: "Licuados",
    descripcion: "Smoothie",
    precio: "1",
  },
  {
    codigo: "8021",
    categoria: "Jugos naturales",
    descripcion: "Jugo de naranja sodín - acompañamiento café ",
    precio: "1",
  },
  {
    codigo: "8022",
    categoria: "Jugos naturales",
    descripcion: "Jugo de naranja  ",
    precio: "1",
  },
  {
    codigo: "8023",
    categoria: "Jugos naturales",
    descripcion: "Limonada en botella individual",
    precio: "1",
  },
  {
    codigo: "8024",
    categoria: "Jugos naturales",
    descripcion: "Limonada en botella 1 litro",
    precio: "1",
  },
  {
    codigo: "2037",
    categoria: "Helado",
    descripcion: "Café helado",
    precio: "1",
  },
  {
    codigo: "2038",
    categoria: "Helado",
    descripcion: "Cold american coffee",
    precio: "1",
  },
  {
    codigo: "2039",
    categoria: "Helado",
    descripcion: "Savage",
    precio: "1",
  },
  {
    codigo: "2040",
    categoria: "Helado",
    descripcion: "Exotic",
    precio: "1",
  },
  {
    codigo: "2008",
    categoria: "Dulce de leche",
    descripcion: "Frapuchino",
    precio: "1",
  },
  {
    codigo: "2006",
    categoria: "Helado",
    descripcion: "Afogato",
    precio: "1",
  },
  {
    codigo: "2018",
    categoria: "Jugo de naranja",
    descripcion: "Orange black",
    precio: "1",
  },
  {
    codigo: "2043",
    categoria: "Vaso descartable",
    descripcion: "Café con leche o solo grande",
    precio: "1",
  },
  {
    codigo: "2057",
    categoria: "Vaso descartable",
    descripcion: "Capuchino/Submarino  ",
    precio: "1",
  },
  {
    codigo: "2047",
    categoria: "Vaso descartable",
    descripcion: "Café solo o con leche Colombiano",
    precio: "1",
  },
  {
    codigo: "2056",
    categoria: "Vaso descartable",
    descripcion: "Café solo o con leche Italiano",
    precio: "1",
  },
  {
    codigo: "2050",
    categoria: "Vaso descartable",
    descripcion: "Café solo o con leche Ethiope",
    precio: "1",
  },
  {
    codigo: "5006",
    categoria: "Extra Combo",
    descripcion: "Extra tostadas",
    precio: "1",
  },
  {
    codigo: "5007",
    categoria: "Extra Combo",
    descripcion: "Tostadas con mermelada y queso",
    precio: "1",
  },
  {
    codigo: "5012",
    categoria: "Extra Combo",
    descripcion: "Extra leche",
    precio: "1",
  },
  {
    codigo: "5008",
    categoria: "Extra Combo",
    descripcion: "Extra large en combos",
    precio: "1",
  },
  {
    codigo: "5005",
    categoria: "Extra Combo",
    descripcion: "Extra queso y mermelada ",
    precio: "1",
  },
  {
    codigo: "5011",
    categoria: "Extra Combo",
    descripcion: "Café italiano",
    precio: "1",
  },
  {
    codigo: "5010",
    categoria: "Extra Combo",
    descripcion: "Café colombiano / ethiope",
    precio: "1",
  },
  {
    codigo: "2074",
    categoria: "Extra Combo",
    descripcion: "Solo café en combo de café con leche + 2 medialunas LSM",
    precio: "1",
  },
];

export const GET: APIRoute = async () => {
  // const articulos = await getArticulos();
  let articulos = [];

  if (MODE === "PRODUCTION") {
    articulos = await getArticulos();
  } else {
    articulos = mockarticulos;
    articulos.shift();
  }
  return new Response(JSON.stringify(articulos), {});
};
